/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as ApiVoicePreviewRouteImport } from './routes/api/voice-preview'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardSectionRouteImport } from './routes/_authenticated/dashboard.$section'
import { Route as AuthenticatedDashboardCallsRouteImport } from './routes/_authenticated/dashboard.calls'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard.messages'
import { Route as ApiPublicAgentTokenRouteImport } from './routes/api/public/agent-token'
import { Route as ApiPublicIncomingCallRouteImport } from './routes/api/public/incoming-call'
import { Route as ApiPublicSquareWebhookRouteImport } from './routes/api/public/square-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiVoicePreviewRoute = ApiVoicePreviewRouteImport.update({
  id: '/api/voice-preview',
  path: '/api/voice-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSectionRoute =
  AuthenticatedDashboardSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCallsRoute =
  AuthenticatedDashboardCallsRouteImport.update({
    id: '/calls',
    path: '/calls',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicAgentTokenRoute = ApiPublicAgentTokenRouteImport.update({
  id: '/api/public/agent-token',
  path: '/api/public/agent-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIncomingCallRoute = ApiPublicIncomingCallRouteImport.update({
  id: '/api/public/incoming-call',
  path: '/api/public/incoming-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSquareWebhookRoute = ApiPublicSquareWebhookRouteImport.update({
  id: '/api/public/square-webhook',
  path: '/api/public/square-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/setup': typeof AuthenticatedSetupRoute
  '/api/voice-preview': typeof ApiVoicePreviewRoute
  '/dashboard/$section': typeof AuthenticatedDashboardSectionRoute
  '/dashboard/calls': typeof AuthenticatedDashboardCallsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/api/public/agent-token': typeof ApiPublicAgentTokenRoute
  '/api/public/incoming-call': typeof ApiPublicIncomingCallRoute
  '/api/public/square-webhook': typeof ApiPublicSquareWebhookRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/api/voice-preview': typeof ApiVoicePreviewRoute
  '/dashboard/$section': typeof AuthenticatedDashboardSectionRoute
  '/dashboard/calls': typeof AuthenticatedDashboardCallsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/api/public/agent-token': typeof ApiPublicAgentTokenRoute
  '/api/public/incoming-call': typeof ApiPublicIncomingCallRoute
  '/api/public/square-webhook': typeof ApiPublicSquareWebhookRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/api/voice-preview': typeof ApiVoicePreviewRoute
  '/_authenticated/dashboard/$section': typeof AuthenticatedDashboardSectionRoute
  '/_authenticated/dashboard/calls': typeof AuthenticatedDashboardCallsRoute
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/api/public/agent-token': typeof ApiPublicAgentTokenRoute
  '/api/public/incoming-call': typeof ApiPublicIncomingCallRoute
  '/api/public/square-webhook': typeof ApiPublicSquareWebhookRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/account'
    | '/dashboard'
    | '/setup'
    | '/api/voice-preview'
    | '/dashboard/$section'
    | '/dashboard/calls'
    | '/dashboard/messages'
    | '/api/public/agent-token'
    | '/api/public/incoming-call'
    | '/api/public/square-webhook'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/account'
    | '/setup'
    | '/api/voice-preview'
    | '/dashboard/$section'
    | '/dashboard/calls'
    | '/dashboard/messages'
    | '/api/public/agent-token'
    | '/api/public/incoming-call'
    | '/api/public/square-webhook'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/setup'
    | '/api/voice-preview'
    | '/_authenticated/dashboard/$section'
    | '/_authenticated/dashboard/calls'
    | '/_authenticated/dashboard/messages'
    | '/api/public/agent-token'
    | '/api/public/incoming-call'
    | '/api/public/square-webhook'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiVoicePreviewRoute: typeof ApiVoicePreviewRoute
  ApiPublicAgentTokenRoute: typeof ApiPublicAgentTokenRoute
  ApiPublicIncomingCallRoute: typeof ApiPublicIncomingCallRoute
  ApiPublicSquareWebhookRoute: typeof ApiPublicSquareWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/voice-preview': {
      id: '/api/voice-preview'
      path: '/api/voice-preview'
      fullPath: '/api/voice-preview'
      preLoaderRoute: typeof ApiVoicePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/$section': {
      id: '/_authenticated/dashboard/$section'
      path: '/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof AuthenticatedDashboardSectionRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/calls': {
      id: '/_authenticated/dashboard/calls'
      path: '/calls'
      fullPath: '/dashboard/calls'
      preLoaderRoute: typeof AuthenticatedDashboardCallsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/agent-token': {
      id: '/api/public/agent-token'
      path: '/api/public/agent-token'
      fullPath: '/api/public/agent-token'
      preLoaderRoute: typeof ApiPublicAgentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/incoming-call': {
      id: '/api/public/incoming-call'
      path: '/api/public/incoming-call'
      fullPath: '/api/public/incoming-call'
      preLoaderRoute: typeof ApiPublicIncomingCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/square-webhook': {
      id: '/api/public/square-webhook'
      path: '/api/public/square-webhook'
      fullPath: '/api/public/square-webhook'
      preLoaderRoute: typeof ApiPublicSquareWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardSectionRoute: typeof AuthenticatedDashboardSectionRoute
  AuthenticatedDashboardCallsRoute: typeof AuthenticatedDashboardCallsRoute
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardSectionRoute: AuthenticatedDashboardSectionRoute,
    AuthenticatedDashboardCallsRoute: AuthenticatedDashboardCallsRoute,
    AuthenticatedDashboardMessagesRoute: AuthenticatedDashboardMessagesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiVoicePreviewRoute: ApiVoicePreviewRoute,
  ApiPublicAgentTokenRoute: ApiPublicAgentTokenRoute,
  ApiPublicIncomingCallRoute: ApiPublicIncomingCallRoute,
  ApiPublicSquareWebhookRoute: ApiPublicSquareWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
