/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as ApiVoicePreviewRouteImport } from './routes/api/voice-preview'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ApiPublicAgentTokenRouteImport } from './routes/api/public/agent-token'
import { Route as ApiPublicIncomingCallRouteImport } from './routes/api/public/incoming-call'
import { Route as ApiPublicSquareWebhookRouteImport } from './routes/api/public/square-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiVoicePreviewRoute = ApiVoicePreviewRouteImport.update({
  id: '/api/voice-preview',
  path: '/api/voice-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentTokenRoute = ApiPublicAgentTokenRouteImport.update({
  id: '/api/public/agent-token',
  path: '/api/public/agent-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIncomingCallRoute = ApiPublicIncomingCallRouteImport.update({
  id: '/api/public/incoming-call',
  path: '/api/public/incoming-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSquareWebhookRoute = ApiPublicSquareWebhookRouteImport.update({
  id: '/api/public/square-webhook',
  path: '/api/public/square-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/api/voice-preview': typeof ApiVoicePreviewRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/public/agent-token': typeof ApiPublicAgentTokenRoute
  '/api/public/incoming-call': typeof ApiPublicIncomingCallRoute
  '/api/public/square-webhook': typeof ApiPublicSquareWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/api/voice-preview': typeof ApiVoicePreviewRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/public/agent-token': typeof ApiPublicAgentTokenRoute
  '/api/public/incoming-call': typeof ApiPublicIncomingCallRoute
  '/api/public/square-webhook': typeof ApiPublicSquareWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/api/voice-preview': typeof ApiVoicePreviewRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/public/agent-token': typeof ApiPublicAgentTokenRoute
  '/api/public/incoming-call': typeof ApiPublicIncomingCallRoute
  '/api/public/square-webhook': typeof ApiPublicSquareWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/setup'
    | '/api/voice-preview'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/api/public/agent-token'
    | '/api/public/incoming-call'
    | '/api/public/square-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/setup'
    | '/api/voice-preview'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/api/public/agent-token'
    | '/api/public/incoming-call'
    | '/api/public/square-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account'
    | '/_authenticated/setup'
    | '/api/voice-preview'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/api/public/agent-token'
    | '/api/public/incoming-call'
    | '/api/public/square-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiVoicePreviewRoute: typeof ApiVoicePreviewRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiPublicAgentTokenRoute: typeof ApiPublicAgentTokenRoute
  ApiPublicIncomingCallRoute: typeof ApiPublicIncomingCallRoute
  ApiPublicSquareWebhookRoute: typeof ApiPublicSquareWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/voice-preview': {
      id: '/api/voice-preview'
      path: '/api/voice-preview'
      fullPath: '/api/voice-preview'
      preLoaderRoute: typeof ApiVoicePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-token': {
      id: '/api/public/agent-token'
      path: '/api/public/agent-token'
      fullPath: '/api/public/agent-token'
      preLoaderRoute: typeof ApiPublicAgentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/incoming-call': {
      id: '/api/public/incoming-call'
      path: '/api/public/incoming-call'
      fullPath: '/api/public/incoming-call'
      preLoaderRoute: typeof ApiPublicIncomingCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/square-webhook': {
      id: '/api/public/square-webhook'
      path: '/api/public/square-webhook'
      fullPath: '/api/public/square-webhook'
      preLoaderRoute: typeof ApiPublicSquareWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiVoicePreviewRoute: ApiVoicePreviewRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiPublicAgentTokenRoute: ApiPublicAgentTokenRoute,
  ApiPublicIncomingCallRoute: ApiPublicIncomingCallRoute,
  ApiPublicSquareWebhookRoute: ApiPublicSquareWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
